# Generated by Django 4.2.7 on 2026-03-09 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0087_rename_woo_credit__source_idx_woo_credit__source_98ac46_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Current credit bank balance in dollars', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_bank_account', to='crm.contact')),
            ],
            options={
                'verbose_name': 'Credit Bank Account',
                'verbose_name_plural': 'Credit Bank Accounts',
                'db_table': 'credit_bank_account',
            },
        ),
        migrations.CreateModel(
            name='CreditBankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit Added'), ('debit', 'Credit Redeemed'), ('adjust', 'Manual Adjustment'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for credits added, negative for debits', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Account balance after this transaction', max_digits=10)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='credit_bank.creditbankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_bank_transactions', to='crm.contact')),
            ],
            options={
                'verbose_name': 'Credit Bank Transaction',
                'verbose_name_plural': 'Credit Bank Transactions',
                'db_table': 'credit_bank_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='credit_bank_custome_b7fdbe_idx'), models.Index(fields=['account', '-created_at'], name='credit_bank_account_6e78be_idx'), models.Index(fields=['transaction_type'], name='credit_bank_transac_5dc0a5_idx'), models.Index(fields=['order_id'], name='credit_bank_order_i_b43cdf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='creditbankaccount',
            index=models.Index(fields=['customer'], name='credit_bank_custome_1ef340_idx'),
        ),
    ]
