# Generated by Django 4.2.7 on 2025-02-20 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='city',
            new_name='billing_city',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='state',
            new_name='billing_state',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='zip',
            new_name='billing_postcode',
        ),
    ]
