# Generated by Django 4.2.7 on 2025-02-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='woo_customer_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
