# Generated by Django 4.2.7 on 2025-03-04 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_product_price_alter_product_regular_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_id', models.CharField(max_length=100, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='ghl_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='ghl_custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contact',
            name='ghl_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contact',
            name='ghl_last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='ghl_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contact',
            name='normalized_phone',
            field=models.CharField(blank=True, help_text='Standardized phone number format', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='primary_source',
            field=models.CharField(choices=[('woo', 'WooCommerce'), ('ghl', 'GoHighLevel'), ('crm', 'CRM')], default='crm', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='woo_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contact',
            name='woo_last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TokenRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('auth', 'Authorization'), ('refresh', 'Refresh Token')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='crm.oauth2token')),
            ],
        ),
    ]
