# Generated by Django 4.2.7 on 2025-03-11 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_oauth2token_contact_ghl_contact_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('woo_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('select', 'Select'), ('text', 'Text'), ('color', 'Color'), ('image', 'Image'), ('button', 'Button')], default='select', max_length=20)),
                ('order_by', models.CharField(choices=[('menu_order', 'Custom ordering'), ('name', 'Name'), ('name_num', 'Name (numeric)'), ('id', 'Term ID')], default='menu_order', max_length=20)),
                ('has_archives', models.BooleanField(default=False)),
                ('woo_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('woo_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parent_id', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('woo_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('woo_id', models.IntegerField()),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('publish', 'Published'), ('private', 'Private'), ('draft', 'Draft'), ('pending', 'Pending')], default='publish', max_length=20)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('stock_status', models.CharField(choices=[('instock', 'In Stock'), ('outofstock', 'Out of Stock'), ('onbackorder', 'On Backorder')], default='instock', max_length=20)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('dimensions', models.JSONField(default=dict)),
                ('attributes', models.JSONField(default=list)),
                ('woo_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='crm.product')),
            ],
            options={
                'verbose_name': 'Product Variation',
                'verbose_name_plural': 'Product Variations',
                'ordering': ['parent_product__name', 'sku'],
                'unique_together': {('woo_id', 'parent_product')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('woo_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('menu_order', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('woo_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='crm.productattribute')),
            ],
            options={
                'verbose_name': 'Product Attribute Term',
                'verbose_name_plural': 'Product Attribute Terms',
                'ordering': ['menu_order', 'name'],
                'unique_together': {('woo_id', 'attribute')},
            },
        ),
    ]
