# Generated by Django 4.2.7 on 2025-03-11 17:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_subscriptionplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bundled_products', models.JSONField(default=list)),
                ('min_quantity', models.IntegerField(default=1)),
                ('max_quantity', models.IntegerField(blank=True, null=True)),
                ('woo_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Bundle',
                'verbose_name_plural': 'Product Bundles',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductGrouped',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grouped_products', models.JSONField(default=list)),
                ('woo_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Grouped',
                'verbose_name_plural': 'Product Grouped',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('period', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=10)),
                ('interval', models.IntegerField(default=1)),
                ('trial_period', models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=10, null=True)),
                ('trial_length', models.IntegerField(blank=True, null=True)),
                ('sign_up_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('woo_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Subscription',
                'verbose_name_plural': 'Product Subscriptions',
                'ordering': ['product__name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='productattributeterm',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productattributeterm',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'ordering': ['product__name'], 'verbose_name': 'Product Variation', 'verbose_name_plural': 'Product Variations'},
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='parent_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='woo_id',
            new_name='woo_variation_id',
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'woo_variation_id')},
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('variable', 'Variable'), ('subscription', 'Subscription'), ('variable_subscription', 'Variable Subscription'), ('bundle', 'Bundle'), ('grouped', 'Grouped')], default='simple', max_length=30),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeTerm',
        ),
        migrations.AddField(
            model_name='productsubscription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='crm.product'),
        ),
        migrations.AddField(
            model_name='productgrouped',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouped_items', to='crm.product'),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='crm.product'),
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='on_sale',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='stock_status',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='weight',
        ),
        migrations.AlterUniqueTogether(
            name='productsubscription',
            unique_together={('product',)},
        ),
        migrations.AlterUniqueTogether(
            name='productgrouped',
            unique_together={('product',)},
        ),
        migrations.AlterUniqueTogether(
            name='productbundle',
            unique_together={('product',)},
        ),
    ]
