# Generated by Django 4.2.7 on 2025-03-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_inventorylocation_productinventory'),
        ('crm', '0009_productbundle_productgrouped_productsubscription_and_more'),
    ]

    operations = [
    ]
