# Generated by Django 4.2.7 on 2025-03-14 11:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_posorder_posorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_card_number', models.BinaryField()),
                ('encrypted_expiry_date', models.BinaryField()),
                ('last4', models.CharField(max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=50)),
                ('cardholder_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to='crm.posorder')),
            ],
            options={
                'verbose_name': 'Payment Card',
                'verbose_name_plural': 'Payment Cards',
            },
        ),
    ]
