# Generated by Django 4.2.7 on 2025-03-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_paymentcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='Shipping address'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='shipping_city',
            field=models.CharField(blank=True, help_text='Shipping city', max_length=100),
        ),
        migrations.AddField(
            model_name='posorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of shipping', max_digits=10),
        ),
        migrations.AddField(
            model_name='posorder',
            name='shipping_country',
            field=models.CharField(blank=True, help_text='Shipping country', max_length=100),
        ),
        migrations.AddField(
            model_name='posorder',
            name='shipping_info',
            field=models.JSONField(blank=True, default=dict, help_text='Shipping carrier and service information'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='shipping_postcode',
            field=models.CharField(blank=True, help_text='Shipping postal code', max_length=20),
        ),
        migrations.AddField(
            model_name='posorder',
            name='shipping_state',
            field=models.CharField(blank=True, help_text='Shipping state/province', max_length=100),
        ),
        migrations.AddField(
            model_name='posorder',
            name='shipping_status',
            field=models.CharField(blank=True, help_text='Status of the shipment', max_length=50),
        ),
        migrations.AddField(
            model_name='posorder',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Shipping tracking number', max_length=100),
        ),
    ]
