# Generated by Django 4.2.7 on 2025-03-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_posorder_shipping_address_posorder_shipping_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Height in inches', max_digits=8),
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='is_digital',
            field=models.BooleanField(default=False, help_text="Whether this is a digital product that doesn't require shipping"),
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Length in inches', max_digits=8),
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight in pounds', max_digits=8),
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Width in inches', max_digits=8),
        ),
    ]
