# Generated by Django 4.2.7 on 2025-03-26 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_posorderitem_height_posorderitem_is_digital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSimple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in pounds', max_digits=8, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in inches', max_digits=8, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in inches', max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in inches', max_digits=8, null=True)),
                ('is_virtual', models.BooleanField(default=False, help_text='Whether this is a virtual product')),
                ('is_downloadable', models.BooleanField(default=False, help_text='Whether this is a downloadable product')),
                ('woo_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_details', to='crm.product')),
            ],
            options={
                'verbose_name': 'Product Simple',
                'verbose_name_plural': 'Product Simple',
                'ordering': ['product__name'],
                'unique_together': {('product',)},
            },
        ),
    ]
