# Generated by Django 4.2.7 on 2025-05-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_productsimple'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='payment_method_title',
            field=models.CharField(blank=True, help_text='Display name for the payment method', max_length=100),
        ),
        migrations.AddField(
            model_name='posorder',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment transaction ID from payment processor', max_length=100),
        ),
    ]
