# Generated by Django 4.2.7 on 2025-07-17 02:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_posorder_payment_method_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name of the location', max_length=255)),
                ('location', models.CharField(help_text='Physical address or description of the location', max_length=255)),
                ('location_id', models.CharField(help_text='Unique identifier for the location (matches GHL location ID)', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'POS Location',
                'verbose_name_plural': 'POS Locations',
                'ordering': ['name'],
            },
        ),
    ]
