# Generated by Django 4.2.7 on 2025-07-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_poslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='poslocation',
            name='assigned_location',
            field=models.CharField(blank=True, help_text='Assigned location for filtering (e.g., Boca Raton, Jupiter, Chicago)', max_length=255, null=True),
        ),
    ]
