# Generated by Django 4.2.7 on 2025-07-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_add_assigned_location_to_pos_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Product brand name', max_length=100),
        ),
    ]
