# Generated by Django 4.2.7 on 2025-07-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='posorder',
            name='assigned_location',
            field=models.CharField(blank=True, help_text='Assigned location for filtering (e.g., Jupiter, Boca Raton, Chicago)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='posorder',
            name='pos_location_id',
            field=models.CharField(blank=True, help_text='Selected POS location ID (matches location_id from localStorage)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posorder',
            name='pos_location_name',
            field=models.CharField(blank=True, help_text='Selected POS location display name', max_length=255, null=True),
        ),
    ]
