# Generated by Django 4.2.7 on 2025-07-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_add_location_fields_to_posorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='pos_location_id',
            field=models.CharField(blank=True, help_text='Selected POS location ID (matches location_id from localStorage)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='pos_location_name',
            field=models.CharField(blank=True, help_text='Selected POS location display name', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Brand name extracted from product attributes', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of brand name', max_length=255, unique=True)),
                ('product_count', models.PositiveIntegerField(default=0, help_text='Number of products with this brand')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this brand is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time this brand was synced from products', null=True)),
            ],
            options={
                'db_table': 'crm_productbrand',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='crm_product_name_42651c_idx'), models.Index(fields=['is_active', 'name'], name='crm_product_is_acti_c21152_idx'), models.Index(fields=['product_count'], name='crm_product_product_7cf083_idx')],
            },
        ),
    ]
