# Generated by Django 4.2.7 on 2025-07-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_posorder_pos_location_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique brand name extracted from product attributes', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the brand name', max_length=255, unique=True)),
                ('product_count', models.PositiveIntegerField(default=0, help_text='Number of products associated with this brand')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this brand is currently active (has products)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this brand was first discovered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this brand was last updated')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this brand was last synced from products', null=True)),
            ],
            options={
                'db_table': 'crm_brand',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='ProductBrand',
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='crm_brand_name_00a658_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active', 'name'], name='crm_brand_is_acti_e857cd_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['product_count'], name='crm_brand_product_adb440_idx'),
        ),
    ]
