# Generated by Django 4.2.7 on 2025-07-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_brand_delete_productbrand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount or percentage applied to this item', max_digits=10),
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('dollar', 'Dollar')], default='dollar', help_text='Type of discount applied', max_length=20),
        ),
    ]
