# Generated by Django 4.2.7 on 2025-07-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_posorderitem_discount_posorderitem_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorderitem',
            name='discount',
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied to this item', max_digits=10),
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='discount_source',
            field=models.CharField(blank=True, help_text="Source of discount (e.g., 'subscription', 'manual', 'coupon')", max_length=50),
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before any discounts', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='posorderitem',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('dollar', 'Dollar')], default='dollar', help_text='Type of discount applied', max_length=10),
        ),
    ]
