# Generated by Django 4.2.7 on 2025-08-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_add_original_price_and_discount_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='billing_country',
            field=models.CharField(blank=True, default='USA', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_via_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_via_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_via_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('', 'Prefer not to say')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='Complete shipping address as formatted string'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
