# Generated by Django 4.2.7 on 2025-08-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_contact_billing_country_contact_contact_via_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_via_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_via_phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_via_sms',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sms_notifications',
        ),
    ]
