# Generated by Django 4.2.7 on 2025-08-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_contact_billing_country_contact_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_postcode',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='use_billing_for_shipping',
        ),
    ]
