# Generated by Django 4.2.7 on 2025-08-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_remove_contact_billing_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='shipping_postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
