# Generated by Django 4.2.7 on 2025-08-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_contact_shipping_address_contact_shipping_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='billing_country',
            field=models.CharField(blank=True, default='USA', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='shipping_same_as_billing',
            field=models.BooleanField(default=True, help_text='Whether shipping address is the same as billing'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='shipping_country',
            field=models.CharField(blank=True, default='USA', max_length=100),
        ),
    ]
