# Generated by Django 4.2.7 on 2025-08-05 06:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_contact_billing_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSOrderRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_number', models.CharField(max_length=100, unique=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.JSONField(blank=True, default=dict)),
                ('payment_method_title', models.CharField(blank=True, help_text='Display name for the refund payment method', max_length=100)),
                ('transaction_id', models.CharField(blank=True, help_text='Refund transaction ID from payment processor', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, help_text='User who created the refund', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('pos_location_id', models.CharField(blank=True, help_text='Selected POS location ID where refund was processed', max_length=100, null=True)),
                ('pos_location_name', models.CharField(blank=True, help_text='Selected POS location display name', max_length=255, null=True)),
                ('assigned_location', models.CharField(blank=True, help_text='Assigned location for filtering', max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='crm.posorder')),
            ],
            options={
                'verbose_name': 'POS Order Refund',
                'verbose_name_plural': 'POS Order Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSOrderRefundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_items', to='crm.posorderitem')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.posorderrefund')),
            ],
            options={
                'verbose_name': 'POS Order Refund Item',
                'verbose_name_plural': 'POS Order Refund Items',
                'ordering': ['name'],
            },
        ),
    ]
