# Generated by Django 4.2.7 on 2025-08-05 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_posorderrefund_posorderrefunditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderrefunditem',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer associated with this refund item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_items', to='crm.contact'),
        ),
    ]
