# Generated by Django 4.2.7 on 2025-08-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_posorderrefunditem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderrefunditem',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Customer email for quick reference without joins', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='posorderrefunditem',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name for quick reference without joins', max_length=255, null=True),
        ),
    ]
