# Generated by Django 4.2.7 on 2025-08-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_posorderrefunditem_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderrefunditem',
            name='refund_reason',
            field=models.TextField(blank=True, help_text='Reason for the refund'),
        ),
    ]
