# Generated by Django 4.2.7 on 2025-08-07 23:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_posorderrefunditem_refund_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='posorderrefund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='WooCreditedService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(help_text='WooCommerce product ID', max_length=100)),
                ('product_name', models.CharField(help_text='Product name for display purposes', max_length=255)),
                ('available_credits', models.IntegerField(default=0, help_text='Number of available credits for this product')),
                ('total_credits', models.IntegerField(default=0, help_text='Total credits purchased for this product')),
                ('used_credits', models.IntegerField(default=0, help_text='Number of credits used for this product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credited_services', to='crm.contact')),
            ],
            options={
                'verbose_name': 'WooCommerce Credited Service',
                'verbose_name_plural': 'WooCommerce Credited Services',
                'db_table': 'woo_credited_services',
                'unique_together': {('contact', 'product_id')},
            },
        ),
    ]
