# Generated by Django 4.2.7 on 2025-08-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_alter_posorder_status_alter_posorderrefund_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WooCreditedService',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contact_ghl_id', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_woo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_fname', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_lname', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_points', models.IntegerField(default=0, help_text='Available credits for this product')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Credited Service',
                'verbose_name_plural': 'Credited Services',
                'unique_together': {('contact_woo_id', 'product_id')},
            },
        ),
        migrations.AddIndex(
            model_name='woocreditedservice',
            index=models.Index(fields=['contact_woo_id'], name='crm_woocred_contact_778730_idx'),
        ),
        migrations.AddIndex(
            model_name='woocreditedservice',
            index=models.Index(fields=['product_id'], name='crm_woocred_product_5e52fd_idx'),
        ),
        migrations.AddIndex(
            model_name='woocreditedservice',
            index=models.Index(fields=['contact_email'], name='crm_woocred_contact_3a143f_idx'),
        ),
    ]
