# Generated by Django 4.2.7 on 2025-08-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_credit_service_points'),
        ('crm', '0037_create_woocreditedservice'),
    ]

    operations = [
    ]
