# Generated by Django 4.2.7 on 2025-08-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_merge_20250816_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditservicepoints',
            options={'verbose_name': 'Credit Service Points', 'verbose_name_plural': 'Credit Service Points'},
        ),
        migrations.RemoveConstraint(
            model_name='creditservicepoints',
            name='unique_customer_product_points',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='atum_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw ATUM inventory data'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='atum_location_id',
            field=models.IntegerField(blank=True, help_text='ATUM Multi-Inventory location ID', null=True),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='atum_location_name',
            field=models.CharField(blank=True, help_text='ATUM location name', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='creditservicepoints',
            unique_together={('customer', 'product')},
        ),
        migrations.AddIndex(
            model_name='creditservicepoints',
            index=models.Index(fields=['customer'], name='csp_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='creditservicepoints',
            index=models.Index(fields=['product'], name='csp_product_idx'),
        ),
        migrations.AddIndex(
            model_name='creditservicepoints',
            index=models.Index(fields=['contact_ghl_id'], name='csp_ghl_id_idx'),
        ),
        migrations.AddIndex(
            model_name='creditservicepoints',
            index=models.Index(fields=['contact_woo_id'], name='csp_woo_id_idx'),
        ),
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['atum_location_id'], name='crm_product_atum_lo_92bc55_idx'),
        ),
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['product', 'atum_location_id'], name='crm_product_product_14e0d8_idx'),
        ),
    ]
