# Generated by Django 4.2.7 on 2025-08-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_alter_creditservicepoints_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productinventory',
            name='crm_product_atum_lo_92bc55_idx',
        ),
        migrations.RemoveIndex(
            model_name='productinventory',
            name='crm_product_product_14e0d8_idx',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='atum_data',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='atum_location_id',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='atum_location_name',
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='atum_barcode',
            field=models.CharField(blank=True, help_text='ATUM location barcode', max_length=100),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='atum_count',
            field=models.IntegerField(default=0, help_text='Number of products in this ATUM location'),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='atum_last_sync',
            field=models.DateTimeField(blank=True, help_text='Last sync from ATUM', null=True),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='atum_location_id',
            field=models.IntegerField(blank=True, help_text='ATUM location ID from WooCommerce', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='atum_parent_id',
            field=models.IntegerField(blank=True, help_text='ATUM parent location ID', null=True),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='atum_slug',
            field=models.CharField(blank=True, help_text='ATUM location slug', max_length=100),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='atum_bbe_date',
            field=models.DateField(blank=True, help_text='ATUM best before date', null=True),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='atum_expiry_days',
            field=models.IntegerField(blank=True, help_text='ATUM expiry days', null=True),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='atum_inbound_stock',
            field=models.IntegerField(default=0, help_text='ATUM inbound stock'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='atum_inventory_id',
            field=models.IntegerField(blank=True, help_text='ATUM inventory record ID', null=True),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='atum_is_main',
            field=models.BooleanField(default=False, help_text='Whether this is the main ATUM inventory'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='atum_last_sync',
            field=models.DateTimeField(blank=True, help_text='Last sync from ATUM', null=True),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='atum_lot',
            field=models.CharField(blank=True, help_text='ATUM lot number', max_length=100),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='atum_priority',
            field=models.IntegerField(default=0, help_text='ATUM inventory priority'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='atum_region',
            field=models.CharField(blank=True, help_text='ATUM region', max_length=100),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='atum_reserved_stock',
            field=models.IntegerField(default=0, help_text='ATUM reserved stock'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='atum_stock_on_hold',
            field=models.IntegerField(default=0, help_text='ATUM stock on hold'),
        ),
    ]
