# Generated by Django 4.2.7 on 2025-08-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_remove_productinventory_crm_product_atum_lo_92bc55_idx_and_more'),
    ]

    operations = [
    ]
