# Generated by Django 4.2.7 on 2025-08-20 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_auto_20250819_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylocation',
            name='atum_barcode',
        ),
        migrations.RemoveField(
            model_name='inventorylocation',
            name='atum_count',
        ),
        migrations.RemoveField(
            model_name='inventorylocation',
            name='atum_last_sync',
        ),
        migrations.RemoveField(
            model_name='inventorylocation',
            name='atum_parent_id',
        ),
        migrations.RemoveField(
            model_name='inventorylocation',
            name='atum_slug',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='atum_bbe_date',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='atum_expiry_days',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='atum_inbound_stock',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='atum_inventory_id',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='atum_is_main',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='atum_last_sync',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='atum_lot',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='atum_priority',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='atum_region',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='atum_reserved_stock',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='atum_stock_on_hold',
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='barcode',
            field=models.CharField(blank=True, help_text='Location barcode', max_length=255),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='parent_location_id',
            field=models.IntegerField(blank=True, help_text='Parent ATUM location ID', null=True),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='product_count',
            field=models.IntegerField(default=0, help_text='Number of products in this location'),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='slug',
            field=models.CharField(blank=True, help_text='URL-friendly location name', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='atum_location_id',
            field=models.IntegerField(blank=True, help_text='ATUM location ID from WooCommerce', null=True),
        ),
        # WebhookLog CreateModel removed - already created in 0043_auto_20250820_1814
    ]
