# Generated by Django 4.2.7 on 2025-08-20 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_auto_20250819_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_type', models.CharField(choices=[('product', 'Product Update'), ('customer', 'Customer Update'), ('order', 'Order Update'), ('inventory', 'Inventory Update'), ('test', 'Test Webhook')], max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='received', max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('request_body', models.TextField(blank=True, help_text='Raw webhook request body')),
                ('woo_product_id', models.IntegerField(blank=True, help_text='WooCommerce product ID if applicable', null=True)),
                ('local_product_id', models.UUIDField(blank=True, help_text='Local product UUID if applicable', null=True)),
                ('action_taken', models.CharField(blank=True, help_text='Action performed (create, update, delete, etc.)', max_length=50)),
                ('updated_fields', models.JSONField(blank=True, default=list, help_text='List of fields that were updated')),
                ('is_bundle_product', models.BooleanField(default=False)),
                ('bundle_sync_attempted', models.BooleanField(default=False)),
                ('bundle_sync_success', models.BooleanField(default=False)),
                ('bundle_items_count', models.IntegerField(blank=True, null=True)),
                ('default_series_updated', models.BooleanField(default=False)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['webhook_type', 'status'], name='crm_webhook_webhook_f8b1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['woo_product_id'], name='crm_webhook_woo_pro_6b7a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['received_at'], name='crm_webhook_receive_5b8c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['is_bundle_product'], name='crm_webhook_is_bund_4e2f1a_idx'),
        ),
    ]
