# Generated by Django 4.2.7 on 2025-08-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_remove_inventorylocation_atum_barcode_and_more'),
        ('crm', '0043_auto_20250820_1814'),
    ]

    operations = [
    ]
