# Generated by Django 4.2.7 on 2025-08-22 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_merge_20250820_1816'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productinventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_locations', to='crm.productvariation'),
        ),
        migrations.AlterUniqueTogether(
            name='productinventory',
            unique_together={('product', 'variation', 'location')},
        ),
    ]
