# Generated by Django 4.2.7 on 2025-08-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_add_variation_to_productinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WooServiceTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('default_index', models.IntegerField()),
                ('series', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'woo_service_types',
            },
        ),
    ]
