# Generated by Django 4.2.7 on 2025-09-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_wooservicetypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wooservicetypes',
            name='default_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wooservicetypes',
            name='series',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
