# Generated by Django 4.2.7 on 2025-09-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_alter_wooservicetypes_default_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WooCreditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('woo_credited_service_id', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=255)),
                ('points_change', models.IntegerField()),
                ('updated_points', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'woo_credit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['woo_credited_service_id'], name='woo_credit__woo_cre_79e6eb_idx'), models.Index(fields=['action'], name='woo_credit__action_cc4430_idx'), models.Index(fields=['order_number'], name='woo_credit__order_n_ace144_idx'), models.Index(fields=['created_at'], name='woo_credit__created_f62b0b_idx')],
            },
        ),
    ]
