# Generated by Django 4.2.7 on 2025-09-10 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0048_woocreditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User-defined name for the saved cart', max_length=255)),
                ('cart_items', models.JSONField(help_text='JSON array of cart items with all their properties')),
                ('order_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Order-level discount amount', max_digits=10, null=True)),
                ('order_discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('dollar', 'Dollar')], default='dollar', help_text='Type of order discount', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who saved the cart', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_carts',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user'], name='saved_carts_user_id_7c5180_idx'), models.Index(fields=['created_at'], name='saved_carts_created_5516e5_idx'), models.Index(fields=['updated_at'], name='saved_carts_updated_d3867c_idx')],
            },
        ),
    ]
