# Generated by Django 4.2.7 on 2025-09-15 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0049_savedcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Setting key (e.g., 'prevent_out_of_stock_cart')", max_length=100, unique=True)),
                ('value', models.TextField(help_text='Setting value (stored as string, converted based on type)')),
                ('setting_type', models.CharField(choices=[('boolean', 'Boolean'), ('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of this setting')),
                ('category', models.CharField(default='general', help_text="Setting category (e.g., 'inventory', 'shipping')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS Setting',
                'verbose_name_plural': 'POS Settings',
                'db_table': 'crm_pos_setting',
            },
        ),
    ]
