# Generated by Django 4.2.7 on 2025-09-17 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_possetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcart',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer associated with this saved cart', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.contact'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['customer'], name='saved_carts_custome_4d406e_idx'),
        ),
    ]
