# Generated by Django 4.2.7 on 2025-09-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_add_customer_to_savedcart'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='savedcart',
            name='saved_carts_custome_4d406e_idx',
        ),
        migrations.AlterField(
            model_name='savedcart',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer associated with the saved cart', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.contact'),
        ),
    ]
