# Generated by Django 4.2.7 on 2025-09-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_add_customer_to_saved_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariation',
            options={'ordering': ['product__name', 'menu_order'], 'verbose_name': 'Product Variation', 'verbose_name_plural': 'Product Variations'},
        ),
        migrations.AddField(
            model_name='productvariation',
            name='menu_order',
            field=models.IntegerField(default=0, help_text='Display order from WooCommerce'),
        ),
    ]
