# Generated by Django 4.2.7 on 2025-09-19 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0053_add_menu_order_to_product_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGeneralNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(help_text='The note content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created the note', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='general_notes', to='crm.contact')),
            ],
            options={
                'db_table': 'customer_general_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='customer_ge_custome_b416a9_idx'), models.Index(fields=['created_by'], name='customer_ge_created_5df55a_idx'), models.Index(fields=['created_at'], name='customer_ge_created_cbf71f_idx')],
            },
        ),
    ]
