# Generated by Django 4.2.7 on 2025-09-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_customergeneralnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='atum_changes_detected',
            field=models.BooleanField(default=False, help_text='Whether ATUM inventory changes were detected in webhook'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='atum_errors',
            field=models.JSONField(blank=True, default=list, help_text='List of ATUM sync errors if any'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='atum_locations_added',
            field=models.IntegerField(blank=True, help_text='Number of ATUM inventory locations added', null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='atum_locations_removed',
            field=models.IntegerField(blank=True, help_text='Number of ATUM inventory locations removed', null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='atum_product_updated',
            field=models.BooleanField(default=False, help_text='Whether the main product ATUM inventory was updated'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='atum_sync_attempted',
            field=models.BooleanField(default=False, help_text='Whether ATUM inventory sync was attempted'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='atum_sync_success',
            field=models.BooleanField(default=False, help_text='Whether ATUM inventory sync completed successfully'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='atum_variations_processed',
            field=models.IntegerField(blank=True, help_text='Number of variations processed for ATUM sync', null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='atum_variations_updated',
            field=models.IntegerField(blank=True, help_text='Number of variations updated during ATUM sync', null=True),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['atum_sync_attempted'], name='crm_webhook_atum_sy_c72d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['atum_changes_detected'], name='crm_webhook_atum_ch_6637c2_idx'),
        ),
    ]
