# Generated by Django 4.2.7 on 2025-10-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_add_atum_webhook_logging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, help_text='Stock quantity. NULL indicates unmanaged stock (ATUM).', null=True),
        ),
    ]
