# Generated by Django 4.2.7 on 2025-10-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0056_allow_null_quantity_unmanaged_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='bundle_products',
            field=models.JSONField(blank=True, default=list, help_text='Original bundle products for receipt display (preserves bundle structure)'),
        ),
    ]
