# Generated by Django 4.2.7 on 2025-10-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_allow_null_bundle_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='fulfillment_location',
            field=models.CharField(blank=True, help_text="Fulfillment location for this item (e.g., 'Dropship', 'Boca Clinic', 'Jupiter Clinic')", max_length=100, null=True),
        ),
    ]
