# Generated by Django 4.2.7 on 2025-10-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_add_fulfillment_location_to_pos_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorderitem',
            name='fulfillment_location',
            field=models.CharField(blank=True, help_text="Fulfillment location for this item (e.g., 'Dropship', 'Boca Clinic', etc.)", max_length=255, null=True),
        ),
    ]
