# Generated by Django 4.2.7 on 2025-10-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_add_fulfillment_location_to_pos_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='brand_mismatch_detected',
            field=models.BooleanField(default=False, help_text='Whether a brand mismatch was detected'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='brand_new_value',
            field=models.CharField(blank=True, help_text='New brand value after sync', max_length=255),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='brand_old_value',
            field=models.CharField(blank=True, help_text='Previous brand value before sync', max_length=255),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='brand_sync_success',
            field=models.BooleanField(default=False, help_text='Whether brand sync completed successfully'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['brand_mismatch_detected'], name='crm_webhook_brand_m_01d72d_idx'),
        ),
    ]
