# Generated by Django 4.2.7 on 2025-10-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0061_add_brand_tracking_to_webhook_log'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='webhooklog',
            name='crm_webhook_brand_m_01d72d_idx',
        ),
        migrations.RemoveField(
            model_name='webhooklog',
            name='brand_mismatch_detected',
        ),
        migrations.RemoveField(
            model_name='webhooklog',
            name='brand_new_value',
        ),
        migrations.RemoveField(
            model_name='webhooklog',
            name='brand_old_value',
        ),
        migrations.RemoveField(
            model_name='webhooklog',
            name='brand_sync_success',
        ),
        migrations.AlterField(
            model_name='posorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='processing', max_length=20),
        ),
    ]
