# Generated by Django 4.2.7 on 2025-10-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0062_change_posorder_default_status_to_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_important_note_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user last acknowledged important notes for this customer', null=True),
        ),
        migrations.AddField(
            model_name='customergeneralnote',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Whether this note is marked as important and should trigger notifications'),
        ),
    ]
