# Generated by Django 4.2.7 on 2025-10-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_add_important_notes_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='update_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed analysis of what was updated, categorized by type (basic_info, pricing, inventory, etc.)'),
        ),
    ]
