# Generated by Django 4.2.7 on 2025-10-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0064_webhooklog_update_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='is_manual_edit',
            field=models.BooleanField(default=True, help_text='Whether this webhook was triggered by manual admin edit (vs automatic system update)'),
        ),
    ]
