# Generated by Django 4.2.7 on 2025-10-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0065_add_is_manual_edit_to_webhook_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooklog',
            name='is_manual_edit',
        ),
    ]
