# Generated by Django 4.2.7 on 2025-10-14 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0066_remove_webhooklog_is_manual_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='trashed_at',
            field=models.DateTimeField(blank=True, help_text='When the order was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='posorder',
            name='trashed_by',
            field=models.ForeignKey(blank=True, help_text='User who trashed this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('trash', 'Trash')], default='processing', max_length=20),
        ),
    ]
