# Generated by Django 4.2.7 on 2025-10-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_add_trash_support_to_pos_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooklog',
            name='webhook_type',
            field=models.CharField(choices=[('product', 'Product Update'), ('customer', 'Customer Update'), ('order', 'Order Update'), ('subscription', 'Subscription Update'), ('subscription_test', 'Subscription Test'), ('inventory', 'Inventory Update'), ('test', 'Test Webhook')], max_length=20),
        ),
    ]
