# Generated by Django 4.2.7 on 2025-11-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_add_subscription_webhook_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending-payment', 'Pending Payment'), ('processing', 'Processing'), ('on-hold', 'On Hold'), ('completed', 'Completed'), ('shipped', 'Shipped'), ('partially-shipped', 'Partially Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('draft', 'Draft'), ('trash', 'Trash')], default='processing', max_length=30),
        ),
    ]
