# Generated by Django 4.2.7 on 2025-12-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0069_add_woocommerce_order_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='discount_reason',
            field=models.TextField(blank=True, help_text="Optional reason/note for the discount (e.g., 'Customer loyalty', 'Price match', etc.)"),
        ),
    ]
