# Generated by Django 4.2.7 on 2026-01-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0070_add_discount_reason_to_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='authorize_net_customer_profile_id',
            field=models.CharField(blank=True, help_text='Authorize.Net customer profile ID - persists even when all cards are deleted', max_length=50, null=True),
        ),
    ]
