# Generated by Django 4.2.7 on 2026-01-21 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0071_add_authorize_net_profile_to_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPointsAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current fractional points balance (e.g., 153.60)', max_digits=10)),
                ('yith_synced_points', models.IntegerField(default=0, help_text='Last integer value synced to YITH (e.g., 153)')),
                ('yith_last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_needed', models.BooleanField(default=False, help_text='Flag to indicate sync to YITH is needed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_account', to='crm.contact')),
            ],
            options={
                'verbose_name': 'Customer Points Account',
                'verbose_name_plural': 'Customer Points Accounts',
                'db_table': 'crm_customer_points_account',
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earn', 'Points Earned'), ('redeem', 'Points Redeemed'), ('adjust', 'Manual Adjustment'), ('expire', 'Points Expired'), ('refund', 'Order Refund'), ('sync', 'YITH Sync Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Change amount (negative for deductions, positive for additions)', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Balance after this transaction', max_digits=10)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='crm.customerpointsaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='crm.contact')),
            ],
            options={
                'verbose_name': 'Points Transaction',
                'verbose_name_plural': 'Points Transactions',
                'db_table': 'crm_points_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='crm_points__custome_0b0c1c_idx'), models.Index(fields=['account', '-created_at'], name='crm_points__account_36d8e3_idx'), models.Index(fields=['transaction_type'], name='crm_points__transac_9634fb_idx'), models.Index(fields=['order_id'], name='crm_points__order_i_f76b7c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customerpointsaccount',
            index=models.Index(fields=['customer'], name='crm_custome_custome_905bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpointsaccount',
            index=models.Index(fields=['sync_needed'], name='crm_custome_sync_ne_52a963_idx'),
        ),
    ]
