# Generated by Django 5.2 on 2026-02-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_customerpointsaccount_pointstransaction_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhooklog',
            new_name='crm_webhook_webhook_89169b_idx',
            old_name='crm_webhook_webhook_f8b1b3_idx',
        ),
        migrations.RenameIndex(
            model_name='webhooklog',
            new_name='crm_webhook_woo_pro_f54ae9_idx',
            old_name='crm_webhook_woo_pro_6b7a5b_idx',
        ),
        migrations.RenameIndex(
            model_name='webhooklog',
            new_name='crm_webhook_receive_af9f9a_idx',
            old_name='crm_webhook_receive_5b8c9d_idx',
        ),
        migrations.RenameIndex(
            model_name='webhooklog',
            new_name='crm_webhook_is_bund_d60b31_idx',
            old_name='crm_webhook_is_bund_4e2f1a_idx',
        ),
    ]
