# Generated by Django 4.2.7 on 2026-02-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0073_rename_crm_webhook_webhook_f8b1b3_idx_crm_webhook_webhook_89169b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='needs_shipping',
            field=models.BooleanField(default=False, help_text='Whether this item needs shipping (for clinic locations like Boca/Jupiter)'),
        ),
    ]
