# Generated by Django 4.2.7 on 2026-02-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0073_woocreditlog_source'),
        ('crm', '0074_add_needs_shipping_to_posorderitem'),
    ]

    operations = [
    ]
