# Generated by Django 5.2 on 2026-02-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0073_woocreditlog_source'),
        ('crm', '0074_add_needs_shipping_to_posorderitem'),
    ]

    operations = [
    ]
