# Generated by Django 4.2.7 on 2026-02-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0075_merge_20260211_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='backorders',
            field=models.CharField(default='no', help_text='no, notify, yes', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='cross_sell_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='date_on_sale_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_on_sale_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manage_stock',
            field=models.BooleanField(blank=True, help_text='Whether stock management is enabled', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='menu_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_class',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_individually',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_class',
            field=models.CharField(blank=True, default='', help_text='standard, reduced-rate, zero-rate', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_status',
            field=models.CharField(default='taxable', help_text='taxable, shipping, none', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='upsell_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='woo_data',
            field=models.JSONField(blank=True, default=dict, help_text='Full WooCommerce product JSON for fields not in dedicated columns'),
        ),
    ]
