# Generated by Django 4.2.7 on 2026-02-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0075_merge_20260212_1344'),
        ('crm', '0076_add_product_editor_fields'),
    ]

    operations = [
    ]
