# Generated by Django 4.2.7 on 2026-02-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0077_merge_20260213_0313'),
        ('crm', '0077_merge_20260213_1544'),
    ]

    operations = [
    ]
