# Generated by Django 4.2.7 on 2026-02-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0078_merge_20260215_0448'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_name', 'first_name'], name='crm_contact_last_na_cda0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['first_name'], name='crm_contact_first_n_3f68c6_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='crm_contact_phone_189db8_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['updated_at'], name='crm_contact_updated_6d80fc_idx'),
        ),
    ]
