# Generated by Django 5.2 on 2026-02-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0077_merge_20260212_2142'),
        ('crm', '0078_merge_20260213_0528'),
        ('crm', '0079_add_contact_search_indexes'),
    ]

    operations = [
    ]
