# Generated by Django 5.2 on 2026-02-16 10:38

from django.db import migrations, models


def safe_rename_or_create_source_index(apps, schema_editor):
    """
    Safely ensure the 'source' index on woo_credit_logs exists with the
    correct auto-generated name. Handles cases where:
    - The old named index exists -> rename it
    - An unnamed index on 'source' already exists -> drop and recreate with correct name
    - No index exists at all -> create it
    """
    new_name = 'woo_credit__source_98ac46_idx'
    old_name = 'woo_credit__source_idx'
    table = 'woo_credit_logs'

    with schema_editor.connection.cursor() as cursor:
        # Check if the new index already exists
        cursor.execute(
            "SELECT 1 FROM pg_indexes WHERE tablename = %s AND indexname = %s",
            [table, new_name],
        )
        if cursor.fetchone():
            return  # Already correct, nothing to do

        # Check if the old named index exists
        cursor.execute(
            "SELECT 1 FROM pg_indexes WHERE tablename = %s AND indexname = %s",
            [table, old_name],
        )
        if cursor.fetchone():
            cursor.execute(
                f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"'
            )
            return

        # Check if any index on the 'source' column exists (different name)
        cursor.execute(
            """
            SELECT indexname FROM pg_indexes
            WHERE tablename = %s AND indexdef LIKE '%%source%%'
              AND indexname != %s
            """,
            [table, new_name],
        )
        row = cursor.fetchone()
        if row:
            existing_name = row[0]
            cursor.execute(
                f'ALTER INDEX "{existing_name}" RENAME TO "{new_name}"'
            )
            return

        # No index exists at all — create it
        cursor.execute(
            f'CREATE INDEX "{new_name}" ON "{table}" ("source")'
        )


def reverse_rename_source_index(apps, schema_editor):
    """Reverse: rename back to the old name if it exists."""
    new_name = 'woo_credit__source_98ac46_idx'
    old_name = 'woo_credit__source_idx'
    table = 'woo_credit_logs'

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_indexes WHERE tablename = %s AND indexname = %s",
            [table, new_name],
        )
        if cursor.fetchone():
            cursor.execute(
                f'ALTER INDEX "{new_name}" RENAME TO "{old_name}"'
            )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0080_merge_20260216_1838'),
    ]

    operations = [
        migrations.RunPython(
            safe_rename_or_create_source_index,
            reverse_rename_source_index,
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='webhook_type',
            field=models.CharField(choices=[('product', 'Product Update'), ('customer', 'Customer Update'), ('order', 'Order Update'), ('subscription', 'Subscription Update'), ('subscription_test', 'Subscription Test'), ('ghl_membership', 'GHL Membership Update'), ('inventory', 'Inventory Update'), ('test', 'Test Webhook')], max_length=20),
        ),
    ]
