# Generated by Django 4.2.7 on 2026-02-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0081_rename_woo_credit__source_idx_woo_credit__source_98ac46_idx_and_more'),
    ]

    operations = [
        # RenameIndex removed — already handled by 0081
        #migrations.RenameIndex(
        #    model_name='woocreditlog',
        #    new_name='woo_credit__source_98ac46_idx',
        #    old_name='woo_credit__source_idx',
        #),
    ]
