# Generated by Django 4.2.7 on 2026-02-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0082_add_payment_card_note'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['authorize_net_customer_profile_id'], name='crm_contact_authori_4c77b3_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['normalized_phone'], name='crm_contact_normali_4b2103_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['woo_order_id'], name='crm_order_woo_ord_be497f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='crm_order_status_51dd80_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='crm_order_created_cd5534_idx'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['status'], name='crm_posorde_status_29581f_idx'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['transaction_id'], name='crm_posorde_transac_7b168b_idx'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['pos_location_id'], name='crm_posorde_pos_loc_8bd19e_idx'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['assigned_location'], name='crm_posorde_assigne_c11c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['created_at'], name='crm_posorde_created_d1ee24_idx'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['trashed_at'], name='crm_posorde_trashed_9386b5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='crm_product_name_949c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='crm_product_product_d7e8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='crm_product_status_0e3145_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_status'], name='crm_product_stock_s_0e0a90_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['updated_at'], name='crm_product_updated_aaa5b8_idx'),
        ),
    ]
