# Generated by Django 4.2.7 on 2026-03-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0086_add_order_discount_reason_to_saved_cart'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='woocreditlog',
            new_name='woo_credit__source_98ac46_idx',
            old_name='woo_credit__source_idx',
        ),
    ]
