# Generated by Django 4.2.7 on 2026-03-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0089_contact_is_active_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost/purchase price from WooCommerce (ATUM _purchase_price)', max_digits=10, null=True),
        ),
    ]
