# Generated by Django 4.2.7 on 2026-03-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0091_add_invoice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='billing_address_2',
            field=models.CharField(blank=True, help_text='Billing address line 2 (apt, suite, unit, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='shipping_address_2',
            field=models.CharField(blank=True, help_text='Shipping address line 2 (apt, suite, unit, etc.)', max_length=255),
        ),
    ]
