# Generated by Django 4.2.7 on 2026-04-14 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0094_ghl_order_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedOrderQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=100)),
                ('failed_step', models.CharField(choices=[('woocommerce_order', 'WooCommerce Order Creation'), ('ghl_sync', 'GHL Membership Sync'), ('credit_points', 'Credit Service Points'), ('receipt', 'Receipt Email')], max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('payment_taken', models.BooleanField(default=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('request_payload', models.JSONField(blank=True, default=dict, help_text='Original request data so the step can be replayed')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('retrying', 'Retrying'), ('resolved', 'Resolved'), ('failed', 'Permanently Failed')], default='queued', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('slack_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('pos_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='failed_queue_entries', to='crm.posorder')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_failed_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Failed Order Queue',
                'verbose_name_plural': 'Failed Order Queue',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='crm_failedo_status_8d98fc_idx'), models.Index(fields=['order_number'], name='crm_failedo_order_n_57d0ea_idx'), models.Index(fields=['failed_step'], name='crm_failedo_failed__a2b7a4_idx'), models.Index(fields=['created_at'], name='crm_failedo_created_9b5821_idx')],
            },
        ),
    ]
