# Generated by Django 4.2.7 on 2026-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0095_failed_order_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedorderqueue',
            name='failed_step',
            field=models.CharField(choices=[('pos_order_save', 'POS Order Save'), ('woocommerce_order', 'WooCommerce Order Creation'), ('ghl_sync', 'GHL Membership Sync'), ('credit_points', 'Credit Service Points'), ('receipt', 'Receipt Email')], max_length=50),
        ),
    ]
