# Generated by Django 4.2.7 on 2025-04-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentcard',
            old_name='card_number_last4',
            new_name='last4',
        ),
        migrations.RemoveField(
            model_name='paymentcard',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='customer_profile_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='payment_profile_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='cardholder_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
