# Generated by Django 4.2.7 on 2025-04-02 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_productsimple'),
        ('payments', '0002_rename_card_number_last4_paymentcard_last4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcard',
            name='cardholder_name',
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='exp_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='exp_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='customer_profile_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='payment_profile_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
