# Generated by Django 4.2.7 on 2025-09-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_paymentcard_cardholder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='billing_country',
            field=models.CharField(blank=True, default='USA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='billing_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='billing_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='billing_zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
