# Generated by Django 4.2.7 on 2026-02-17 10:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0082_add_payment_card_note'),
        ('payments', '0004_add_billing_address_to_payment_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCardNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_profile_id', models.CharField(db_index=True, max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_card_notes', to='crm.contact')),
            ],
            options={
                'verbose_name': 'Payment Card Note',
                'verbose_name_plural': 'Payment Card Notes',
                'unique_together': {('customer', 'payment_profile_id')},
            },
        ),
    ]
