# Generated by Django 5.2 on 2026-02-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ghl_user_id',
            field=models.CharField(blank=True, help_text='GoHighLevel User ID for this POS user', max_length=100, null=True),
        ),
    ]
