# Generated by Django 4.2.7 on 2026-03-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_role_permission_fields_and_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='can_manage_inventory',
            field=models.BooleanField(default=False, help_text='Manage inventory levels and ATUM locations'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='can_manage_products',
            field=models.BooleanField(default=False, help_text='Edit products in Settings'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='can_manage_settings',
            field=models.BooleanField(default=False, help_text='Access Store Settings and Integrations'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='can_manage_users',
            field=models.BooleanField(default=False, help_text='Manage users and roles in Settings'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='can_process_orders',
            field=models.BooleanField(default=True, help_text='Create/submit POS orders'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='can_view_reports',
            field=models.BooleanField(default=False, help_text='Access Reports view'),
        ),
    ]
