# Generated by Django 4.2.7 on 2026-02-17 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0082_add_payment_card_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlanTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name, e.g. '50/25/25 over 3 months'", max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('num_installments', models.PositiveIntegerField(help_text='Total number of installments including the first payment')),
                ('installments_config', models.JSONField(help_text='Array of {percentage: number, offset_days: number} for each installment')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plan_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Plan Template',
                'verbose_name_plural': 'Payment Plan Templates',
                'db_table': 'payment_plan_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_number', models.CharField(help_text='e.g. PP-10001', max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Full order total', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('defaulted', 'Defaulted')], default='active', max_length=20)),
                ('payment_method', models.JSONField(blank=True, default=dict, help_text='Saved card info for auto-billing: {customer_profile_id, payment_profile_id, last4, brand}')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_plans', to=settings.AUTH_USER_MODEL)),
                ('pos_order', models.OneToOneField(help_text='The POS order this plan covers', on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='crm.posorder')),
                ('template', models.ForeignKey(blank=True, help_text='Null if custom plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='payment_plans.paymentplantemplate')),
            ],
            options={
                'verbose_name': 'Payment Plan',
                'verbose_name_plural': 'Payment Plans',
                'db_table': 'payment_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlanInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField(help_text='1-indexed installment number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.JSONField(blank=True, default=dict, help_text='Payment method used for this installment (may differ from plan default)')),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payment_plans.paymentplan')),
            ],
            options={
                'verbose_name': 'Payment Plan Installment',
                'verbose_name_plural': 'Payment Plan Installments',
                'db_table': 'payment_plan_installment',
                'ordering': ['installment_number'],
                'unique_together': {('plan', 'installment_number')},
            },
        ),
    ]
