# Generated by Django 4.2.7 on 2026-02-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplaninstallment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
