# Generated by Django 4.2.7 on 2026-03-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_plans', '0002_add_overdue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original order amount before service charge', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='service_charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated service charge dollar amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='service_charge_type',
            field=models.CharField(default='none', help_text='Type of service charge applied: none, percentage, flat', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='service_charge_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Service charge value used (percentage or flat amount)', max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentplaninstallment',
            name='card_override',
            field=models.JSONField(blank=True, default=dict, help_text='Per-installment card override for auto-billing: {customer_profile_id, payment_profile_id, last4, brand}. If empty, uses plan default.'),
        ),
        migrations.AddField(
            model_name='paymentplantemplate',
            name='service_charge_type',
            field=models.CharField(choices=[('none', 'No Service Charge'), ('percentage', 'Percentage'), ('flat', 'Flat Fee')], default='none', help_text='Type of service charge: none, percentage, or flat fee', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentplantemplate',
            name='service_charge_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Service charge value: percentage (e.g. 5.00 for 5%) or flat amount (e.g. 500.00)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='payment_method',
            field=models.JSONField(blank=True, default=dict, help_text='Default card for auto-billing: {customer_profile_id, payment_profile_id, last4, brand}'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Full plan total including service charge', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentplaninstallment',
            name='payment_method',
            field=models.JSONField(blank=True, default=dict, help_text='Payment method used/recorded for this installment after payment'),
        ),
    ]
